version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@3.0.0
  aws-ecs: circleci/aws-ecs@0.0.6
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts-13.24
    #    parallelism: 4
    steps:
      - checkout
      - restore_cache:
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          name: Restore Cached Dependencies
          keys:
            - penrose-cache-{{ checksum "penrose.cabal" }}
      - run:
          name: Manually install Alex and Happy
          command: stack install alex happy
      - run:
          name: Resolve/Update Dependencies
          command: stack build
      - run:
          name: Run tests
          command: stack test
      - run:
          name: Install executable
          command: stack install --ghc-options="-O2 -static -threaded"
      - save_cache:
          name: Cache Dependencies
          key: penrose-cache-{{ checksum "penrose.cabal" }}
          paths:
            - ".stack"
            - ".stack-work"
            - "$HOME/.ghc"
            - "$HOME/.cabal"
            - "$HOME/.stack"

      - store_artifacts:
          # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: ~/.local/bin/penrose
          destination: penrose-bin
      - persist_to_workspace:
          root: ~/.local/bin
          paths:
            - penrose
      - persist_to_workspace:
          root: .
          paths:
            - src/

workflows:
  version: 2.1
  build_other_branches:
    jobs:
      - build:
        filters:
          branches:
            ignore:
              - master
  build_master_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - aws-ecr/build_and_push_image:
          filters:
            branches:
              only: master
          requires:
            - build
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          region: AWS_REGION
          repo: penrose
          dockerfile: Dockerfile.circleci
          attach-workspace: true
#       - aws-ecs/deploy-service-update:
#           requires:
#             - aws-ecr/build_and_push_image
#           family: penrose-service
#           cluster-name: penrose-cluster
#           aws-access-key-id: $AWS_ACCESS_KEY
#           aws-secret-access-key: $AWS_SECRET_ACCESS_KEY
#           aws-region: $AWS_REGION
#           filters:
#             branches:
#               only: master
