[package]
name = "penrose-optimizer"
version = "2.2.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
console_error_panic_hook = "0.1"
console_log = "0.2"
js-sys = "0.3"
log = "0.4"
nalgebra = "0.31"
serde = { version = "1", features = ["derive"] }
serde-wasm-bindgen = "0.4"
ts-rs = "6"
wasm-bindgen = "=0.2.84"
